### ISSUE TITLE
Missing RG:b:

### ISSUE THREAD

**Issue by wbv** [kaliRegenold/PhotoManip#1]
Like title says, there is no RG:b: control over the "weights" of each channel.

**Comment by kaliRegenold** [comment]
@wbv 
That's in the TODO.
The image is opened as a grayscale Mat, so the code will work with an RGB image coming in.

**Comment by wbv** [comment]
![kalireact](https://user-images.githubusercontent.com/7481569/47795071-5ec00a00-dce7-11e8-9d88-f3adee1fb6db.png)
